services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Weasel\TestBench\UseCase\Pet\Api\CreatePet:
    class: Weasel\TestBench\UseCase\Pet\Service\CreatePet