services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Weasel\TestBench\WebApi\Pet\Service\GetPets:
    public: true

  Weasel\TestBench\WebApi\Pet\Service\CreatePet:
    public: true

  Weasel\TestBench\WebApi\Pet\Service\MapPetToData:

  Weasel\TestBench\WebApi\Pet\Service\MapPetsToDataArray:

